language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - "pip install -U pip"
# command to install dependencies
install:
  - "pip install ."
  - "pip install -U -r test_requirements.txt"
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install black; fi
# command to run tests
script:
  - pytest
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then black --check .; fi
notifications:
  email: false
